channels:
  # - fastchan
  - fastai
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.1.1
  - fastai=2.5.3
  - fastcore=1.3.26
  - flake8=3.9.2
  - matplotlib=3.4.3
  - notebook=6.4.6
  - pandas=1.3.3
  - python=3.9
  - pyyaml=5.4.1
  - scikit-learn=1.0.1
  - seaborn=0.11.2
  - statsmodels=0.13.0
