seed: 42
# data
target: 'all'
perc_val: 0.1
grouped: true
stratify: false
batch_size: Null
ohe: true
# Rescaling
rescaleX: 'minmax'
rescaleY: 'minmax'
# model
bn: False
pdrop: 0.
act: 'sigmoid'
neurons_l1: 16
neurons_l2: 16
neurons_l3: 0
neurons_l4: 0
neurons_l5: 0
neurons_l6: 0
neurons_l7: 0
range_eps: 0.5
# train
split_seeds: [1, 12, 123, 1234, 12345]
kernel_init: 'orthogonal'
bias_init: 'default'
loss: 'msesigmatotal'
coeff_sigma_total: 1.5
coeff_sigma_between: 1.5
coeff_sigma_within: 2
coeff_mse: 1
opt: 'adam_decoupled'
fit_func: 'normal'
cycle_perc_start: 0.25
lr: 0.1
reg_l2: 0
epochs: 20000
patience: 2000
monitor: 'valid_loss'
